language: node_js

node_js:
  - lts/*

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install

# In order to avoid double build on pull requests,
# only build on pushes on master and on pushes on pull requests
branches:
  only:
    - master

stages:
  - test
  - name: demo
    if: type != pull_request AND branch = master
  - name: release
    if: type != pull_request AND branch = master

jobs:
  include:
    - stage: test
      script:
        - npx danger ci
        - npm run lint
        - npm run test:unit -- --runInBand
        - npm run test:e2e -- --headless

    - stage: demo
      script: npm run build:demo
      deploy:
        skip_cleanup: true
        provider: surge
        project: ./dist/
        domain: vue-live.surge.sh

    - stage: release
      script:
        - npm run build
        - npx semantic-release
