os: linux
arch:
  - arm64
  - ppc64le
  - s390x

language: node_js

# Cypress,io 3.4.1 needs this lib to keep working on travis CI
addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

node_js:
  - lts/*

# In order to avoid double build on pull requests,
# only build on pushes on master and on pushes on pull requests
branches:
  only:
    - master

stages:
  - test
  - name: demo
    if: type != pull_request AND branch = master
  - name: release
    if: type != pull_request AND branch = master

jobs:
  include:
    - stage: test
      script:
        - npx danger ci
        - npm run lint
        - npm run test:unit -- --runInBand
        - npm run test:e2e -- --headless

    - stage: demo
      script: npm run build:demo
      deploy:
        skip_cleanup: true
        provider: surge
        project: ./dist/
        domain: vue-live.surge.sh

    - stage: release
      script:
        - npm run build
        - npx semantic-release
